actions:
  black:
    run: black --check --diff {files}
    fix: black {files}
    include: "*.py"

  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude: "docs/"

  yarn-audit:
    run: yarn audit

  missing-migirations:
    include: "*.py"
    run: |
      ./manage.py makemigrations --check --no-input --dry-run recipes studies || (
        echo "You probably have migrations that need to be created" && exit 1
      )

  poetry-check:
    include:
      - "pyproject.toml"
      - "poetry.lock"
    run: poetry check --no-interaction

shortcuts:
  lint:
    flags:
      - include-unstaged
      - include-untracked
  "lint:all":
    extends: lint
    flags: use-tracked-files
  fix:
    extends: lint
    flags: fix
  "fix:all":
    extends: fix
    flags: use-tracked-files
