actions:
  black:
    run: black --check --diff {files}
    fix: black {files}
    include: "*.py"

  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude: "docs/"

  sort-requirements:
    run: sort-requirements --check {files}
    fix: sort-requirements {files}
    include: "requirements/*.txt"

  eslint:
    run: yarn eslint {files}
    fix: yarn eslint --fix {files}
    include:
      - "*.js"
      - "*.jsx"
    exclude:
      - ".eslintrc.js"

  yarn-audit:
    run: yarn audit
shortcuts:
  lint:
    flags:
      - include-unstaged
      - include-untracked
  "lint:all":
    extends: lint
    flags: use-tracked-files
  fix:
    extends: lint
    flags: fix
  "fix:all":
    extends: fix
    flags: use-tracked-files
