actions:
  black:
    run: black --check --diff {files}
    fix: black {files}
    include: "*.py"

  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude: "docs/"

  eslint:
    run: eslint {files}
    fix: eslint --fix {files}
    include:
      - "*.js"
      - "*.jsx"
    exclude:
      - ".eslintrc.js"
