status = [
  "ci/circleci: lint",
  "ci/circleci: build-test-publish",
  "ci/circleci: docs-build"
]
# Avoid including verbose details from PR bodies
cut_body_after = "\n---\n"
block_labels = ["bors-dont-merge"]
required_approvals = 1
delete_merged_branches = true 
