status = [
  "ci/circleci: build_test_publish",
  "ci/circleci: docs"
]
# Avoid including verbose details from PR bodies
cut_body_after = "---"
block_labels = ["bors-dont-merge"]
required_approvals = 1
delete_merged_branches = true 
