version: '2'

services:
  database:
    extends:
      file: normandy-base.yml
      service: database

  normandy:
    extends:
      file: normandy-base.yml
      service: normandy-base
    links:
      - database
      - autograph
    volumes:
      - ../:/app
    environment:
      DJANGO_CONFIGURATION: Development

  watcher:
    extends:
      file: normandy-base.yml
      service: normandy-base
    volumes:
      - ../:/app
    command: npm run watch

  proxy:
    extends:
      file: normandy-base.yml
      service: proxy
    links:
      - normandy

  autograph:
    extends:
      file: normandy-base.yml
      service: autograph
