version: '2'

services:
  database:
    image: postgres:9.5.2

  normandy-base:
    image: mozilla/normandy:latest
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      DATABASE_URL: "postgres://postgres@database/postgres"
      DJANGO_CONFIGURATION: ProductionInsecure
      DJANGO_AUTOGRAPH_URL: http://autograph:8000/
      # From etc/autograph.yaml
      DJANGO_AUTOGRAPH_HAWK_ID: normandev
      DJANGO_AUTOGRAPH_HAWK_SECRET_KEY: 3dhoaupudifjjvm7xznd9bn73159xn3xwr77b61kzdjwzzsjts
      DJANGO_CAN_EDIT_ACTIONS_IN_USE: "true"
      # Pulled from the local environment
      DJANGO_API_CACHE_ENABLED:
    stop_signal: SIGKILL
 
  proxy:
    image: nginx:1.9.14
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/proxy.crt:/etc/nginx/proxy.crt:ro
      - ./etc/proxy.key:/etc/nginx/proxy.key:ro

  autograph:
    image: mozilla/autograph
    stop_signal: SIGKILL
    volumes:
      - ./etc/autograph.yaml:/etc/autograph/autograph.yaml:ro
    ports:
        - "8000"
