version: "3"

services:
  db:
    image: postgres:9.6
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: normandy:web
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DJANGO_CONFIGURATION=ProductionInsecure
      - DATABASE_URL=postgres://postgres@db/postgres
      - ARTIFACTS_PATH=/artifacts
    volumes:
      - test-artifacts:/artifacts
    command: first-start

  artifact-collector:
    image: ubuntu:18.04 # TODO this could be a more minimal image
    volumes:
      - test-artifacts:/artifacts
    command: |
      bash -c "
        chmod -R 777 /artifacts
        echo Waiting for artifacts
        sleep 1h  # Wait a long time "

  js-tests:
    image: normandy:web
    user: root
    ports:
      - 9876:9876
    environment:
      - ARTIFACTS_PATH=/artifacts
    volumes:
      - test-artifacts:/artifacts
    command: js-tests

  js-tests-browser:
    build:
      context: .
      dockerfile: js-tests-browser.Dockerfile
    # The test runner starts listening on the port slightly before it starts
    # acceptions requests. Waiting a second makes this work more reliably.
    command: |
      bash -c "
        ./wait-for-it.sh -t 30 js-tests:9876
        sleep 5
        firefox js-tests:9876 --headless "

volumes:
  ? test-artifacts
