version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile.development
    image: normandy:web
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - CI
      - DJANGO_CONFIGURATION=Development
      - DATABASE_URL=postgres://postgres@db/postgres
      - ARTIFACTS_PATH=/artifacts
    volumes:
      - test-artifacts:/artifacts
    command: first-start